// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/repository (interfaces: BatchRepo)
//
// Generated by this command:
//
//	mockgen -destination=mock/mock_batch.go -package=mock_repo ./internal/repository BatchRepo
//

// Package mock_repo is a generated GoMock package.
package mock_repo

import (
	context "context"
	reflect "reflect"

	repository "github.com/IvanOplesnin/url-shortener/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockBatchRepo is a mock of BatchRepo interface.
type MockBatchRepo struct {
	ctrl     *gomock.Controller
	recorder *MockBatchRepoMockRecorder
	isgomock struct{}
}

// MockBatchRepoMockRecorder is the mock recorder for MockBatchRepo.
type MockBatchRepoMockRecorder struct {
	mock *MockBatchRepo
}

// NewMockBatchRepo creates a new mock instance.
func NewMockBatchRepo(ctrl *gomock.Controller) *MockBatchRepo {
	mock := &MockBatchRepo{ctrl: ctrl}
	mock.recorder = &MockBatchRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBatchRepo) EXPECT() *MockBatchRepoMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockBatchRepo) Add(ctx context.Context, key repository.ShortURL, value repository.URL) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockBatchRepoMockRecorder) Add(ctx, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockBatchRepo)(nil).Add), ctx, key, value)
}

// AddMany mocks base method.
func (m *MockBatchRepo) AddMany(ctx context.Context, records []repository.ArgAddMany) ([]repository.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddMany", ctx, records)
	ret0, _ := ret[0].([]repository.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddMany indicates an expected call of AddMany.
func (mr *MockBatchRepoMockRecorder) AddMany(ctx, records any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddMany", reflect.TypeOf((*MockBatchRepo)(nil).AddMany), ctx, records)
}

// Get mocks base method.
func (m *MockBatchRepo) Get(ctx context.Context, key repository.ShortURL) (repository.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(repository.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockBatchRepoMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockBatchRepo)(nil).Get), ctx, key)
}

// GetByURLs mocks base method.
func (m *MockBatchRepo) GetByURLs(ctx context.Context, urls []string) ([]repository.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByURLs", ctx, urls)
	ret0, _ := ret[0].([]repository.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByURLs indicates an expected call of GetByURLs.
func (mr *MockBatchRepoMockRecorder) GetByURLs(ctx, urls any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByURLs", reflect.TypeOf((*MockBatchRepo)(nil).GetByURLs), ctx, urls)
}

// Search mocks base method.
func (m *MockBatchRepo) Search(ctx context.Context, url repository.URL) (repository.ShortURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, url)
	ret0, _ := ret[0].(repository.ShortURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockBatchRepoMockRecorder) Search(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockBatchRepo)(nil).Search), ctx, url)
}
