// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/repo.go
//
// Generated by this command:
//
//	mockgen -source=internal/repository/repo.go -destination=mock/mock_repo.go -package=mock_repo
//

// Package mock_repo is a generated GoMock package.
package mock_repo

import (
	context "context"
	reflect "reflect"

	repository "github.com/IvanOplesnin/url-shortener/internal/repository"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockRepository) Add(ctx context.Context, key repository.ShortURL, value repository.URL) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockRepositoryMockRecorder) Add(ctx, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockRepository)(nil).Add), ctx, key, value)
}

// Get mocks base method.
func (m *MockRepository) Get(ctx context.Context, key repository.ShortURL) (repository.URL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(repository.URL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRepositoryMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepository)(nil).Get), ctx, key)
}

// Search mocks base method.
func (m *MockRepository) Search(ctx context.Context, url repository.URL) (repository.ShortURL, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, url)
	ret0, _ := ret[0].(repository.ShortURL)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockRepositoryMockRecorder) Search(ctx, url any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockRepository)(nil).Search), ctx, url)
}

// MockSeeder is a mock of Seeder interface.
type MockSeeder struct {
	ctrl     *gomock.Controller
	recorder *MockSeederMockRecorder
	isgomock struct{}
}

// MockSeederMockRecorder is the mock recorder for MockSeeder.
type MockSeederMockRecorder struct {
	mock *MockSeeder
}

// NewMockSeeder creates a new mock instance.
func NewMockSeeder(ctrl *gomock.Controller) *MockSeeder {
	mock := &MockSeeder{ctrl: ctrl}
	mock.recorder = &MockSeederMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeeder) EXPECT() *MockSeederMockRecorder {
	return m.recorder
}

// Seed mocks base method.
func (m *MockSeeder) Seed(arg0 []repository.Record) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Seed", arg0)
}

// Seed indicates an expected call of Seed.
func (mr *MockSeederMockRecorder) Seed(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Seed", reflect.TypeOf((*MockSeeder)(nil).Seed), arg0)
}

// MockSnapshoter is a mock of Snapshoter interface.
type MockSnapshoter struct {
	ctrl     *gomock.Controller
	recorder *MockSnapshoterMockRecorder
	isgomock struct{}
}

// MockSnapshoterMockRecorder is the mock recorder for MockSnapshoter.
type MockSnapshoterMockRecorder struct {
	mock *MockSnapshoter
}

// NewMockSnapshoter creates a new mock instance.
func NewMockSnapshoter(ctrl *gomock.Controller) *MockSnapshoter {
	mock := &MockSnapshoter{ctrl: ctrl}
	mock.recorder = &MockSnapshoterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSnapshoter) EXPECT() *MockSnapshoterMockRecorder {
	return m.recorder
}

// Snapshot mocks base method.
func (m *MockSnapshoter) Snapshot() []repository.Record {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshot")
	ret0, _ := ret[0].([]repository.Record)
	return ret0
}

// Snapshot indicates an expected call of Snapshot.
func (mr *MockSnapshoterMockRecorder) Snapshot() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshot", reflect.TypeOf((*MockSnapshoter)(nil).Snapshot))
}

// MockRollback is a mock of Rollback interface.
type MockRollback struct {
	ctrl     *gomock.Controller
	recorder *MockRollbackMockRecorder
	isgomock struct{}
}

// MockRollbackMockRecorder is the mock recorder for MockRollback.
type MockRollbackMockRecorder struct {
	mock *MockRollback
}

// NewMockRollback creates a new mock instance.
func NewMockRollback(ctrl *gomock.Controller) *MockRollback {
	mock := &MockRollback{ctrl: ctrl}
	mock.recorder = &MockRollbackMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRollback) EXPECT() *MockRollbackMockRecorder {
	return m.recorder
}

// Remove mocks base method.
func (m *MockRollback) Remove(arg0 repository.ShortURL, arg1 repository.URL) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Remove", arg0, arg1)
}

// Remove indicates an expected call of Remove.
func (mr *MockRollbackMockRecorder) Remove(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockRollback)(nil).Remove), arg0, arg1)
}
