// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"time"

	"github.com/IvanOplesnin/url-shortener/internal/repository"
	"github.com/jackc/pgx/v5/pgtype"
)

type AliasUrl struct {
	ID        int64
	UserID    pgtype.Int8
	URL       repository.URL
	ShortURL  repository.ShortURL
	CreatedAt time.Time
}

type User struct {
	ID int64
}
