// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package query

import (
	"time"

	"github.com/IvanOplesnin/url-shortener/internal/repository"
)

type AliasUrl struct {
	ID        int64
	URL       repository.URL
	ShortURL  repository.ShortURL
	CreatedAt time.Time
}
