// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package query

import (
	"context"
	"time"

	"github.com/IvanOplesnin/url-shortener/internal/repository"
)

const add = `-- name: Add :exec
INSERT INTO alias_url (
    short_url, "url", created_at
) VALUES (
    $1, $2, $3
)
`

type AddParams struct {
	ShortURL  repository.ShortURL
	URL       repository.URL
	CreatedAt time.Time
}

func (q *Queries) Add(ctx context.Context, arg AddParams) error {
	_, err := q.db.Exec(ctx, add, arg.ShortURL, arg.URL, arg.CreatedAt)
	return err
}

const get = `-- name: Get :one
SELECT "url"
FROM alias_url
WHERE short_url = $1
`

func (q *Queries) Get(ctx context.Context, shortUrl repository.ShortURL) (repository.URL, error) {
	row := q.db.QueryRow(ctx, get, shortUrl)
	var url repository.URL
	err := row.Scan(&url)
	return url, err
}

const getAllRecords = `-- name: GetAllRecords :many
SELECT id, url, short_url, created_at 
FROM alias_url
ORDER BY id
`

func (q *Queries) GetAllRecords(ctx context.Context) ([]AliasUrl, error) {
	rows, err := q.db.Query(ctx, getAllRecords)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AliasUrl
	for rows.Next() {
		var i AliasUrl
		if err := rows.Scan(
			&i.ID,
			&i.URL,
			&i.ShortURL,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const search = `-- name: Search :one
SELECT short_url 
FROM alias_url
WHERE "url" = $1
LIMIT 1
`

func (q *Queries) Search(ctx context.Context, url repository.URL) (repository.ShortURL, error) {
	row := q.db.QueryRow(ctx, search, url)
	var short_url repository.ShortURL
	err := row.Scan(&short_url)
	return short_url, err
}
